### ISSUE TITLE
Feature: webfont

### ISSUE THREAD

**Issue by evanbutera** [BrianDGLS/node-hologram#12]
Allow user to add webfonts inside docs

either as options array (easier implementation) 
e.g.

`customFonts : ['url', 'another_url']`

or as doc element
e.g.
```
/*doc
<customFonts>
<link href='https://fonts.googleapis.com/css?family=' rel='stylesheet' type='text/css'>
</customFonts>
*/
```

related to #6 - configuration in doc

**Comment by BrianDGLS** [comment]
Closed as #13 is merged to develop.
