### ISSUE TITLE
Iframe sizing

### ISSUE THREAD

**Issue by evanbutera** [BrianDGLS/node-hologram#9]
Iframes will have a wrong height value if an element has no defined dimensions - i.e. external image

Possible solutions: 
bubbling an event from iframe to parent document to force resize;
rework layout;

**Comment by BrianDGLS** [comment]
Not sure how much we can do in regards to this, the issue is the iframe itself.

I'll have a play around but I think the best option is just having a larger default height.

I'll also take a look at the resize function and see if there is anything else that I can add to account for this.

**Comment by evanbutera** [comment]
I've messed around with the code, As far as i can see, any event within the iframe will trigger a resize.
Tho, hot the most elegant solution (indeed i hate myself for thinking suck a thing), but triggering a click event after a timeout can work just fine.

Also, hologram could provide a generator for image assets, allowing the use of a `src="{{svg}}"` code inside <example>.

This code could be converted into a simple svg placeholder.

Ill check around for some other solutions.

**Comment by evanbutera** [comment]
made resizable the iframe on FEATURE/THEME
